import pytest
import json
import os
from src.indexer import Indexer

# --- Fixtures ---

@pytest.fixture
def sample_crawled_data():
    """Provides mock crawler output with varied cases and punctuation."""
    return [
        {
            'url': 'http://quotes.toscrape.com/page/1/',
            'text': 'Hello world! Hello, WORLD.'
        },
        {
            'url': 'http://quotes.toscrape.com/page/2/',
            'text': 'Testing... one, two. ONE.'
        }
    ]

@pytest.fixture
def indexer(tmp_path):
    """
    Provides an Indexer instance. 
    Uses pytest's tmp_path to save the index to a temporary directory 
    so we don't overwrite the real index.json during testing.
    """
    # tmp_path creates a unique temporary folder for the test run
    test_index_path = tmp_path / "data" / "index.json"
    return Indexer(index_file_path=str(test_index_path))

# --- Tests ---

def test_build_index_case_and_punctuation(indexer, sample_crawled_data):
    """Tests that text is correctly lowercased and stripped of punctuation."""
    index = indexer.build_index(sample_crawled_data)
    
    # 'Hello', 'world!', and 'WORLD.' should all resolve to lowercase, clean keys
    assert 'hello' in index
    assert 'world' in index
    assert 'hello,' not in index 
    assert 'world!' not in index
    assert 'WORLD' not in index

def test_build_index_statistics(indexer, sample_crawled_data):
    """Tests that word frequencies and positions are calculated correctly."""
    index = indexer.build_index(sample_crawled_data)
    url1 = 'http://quotes.toscrape.com/page/1/'
    url2 = 'http://quotes.toscrape.com/page/2/'
    
    # 'hello' is at index 0 and 2 on page 1
    assert index['hello'][url1]['frequency'] == 2
    assert index['hello'][url1]['positions'] == [0, 2]
    
    # 'world' is at index 1 and 3 on page 1
    assert index['world'][url1]['frequency'] == 2
    assert index['world'][url1]['positions'] == [1, 3]

    # 'one' is at index 1 and 3 on page 2
    assert index['one'][url2]['frequency'] == 2
    assert index['one'][url2]['positions'] == [1, 3]

def test_save_index_creates_file(indexer, sample_crawled_data):
    """Tests that the indexer correctly writes the JSON dictionary to disk."""
    # Build the index first so there is data to save
    indexer.build_index(sample_crawled_data)
    
    # Trigger the save operation
    indexer.save_index()
    
    # Assert the file was actually created at the expected path
    assert os.path.exists(indexer.index_file_path)
    
    # Open the newly created file to verify its contents
    with open(indexer.index_file_path, 'r', encoding='utf-8') as f:
        saved_data = json.load(f)
        
    # The data loaded from the JSON file should perfectly match the dictionary in memory
    assert saved_data == indexer.inverted_index
    assert saved_data['hello']['http://quotes.toscrape.com/page/1/']['frequency'] == 2

# Add own test to test empty text.
def test_empty_text(indexer):
    data = [{'url': 'test', 'text': ''}]
    index = indexer.build_index(data)
    assert index == {}

# Add own test for a repeated build crawl.
def test_build_index_resets(indexer, sample_crawled_data):
    indexer.build_index(sample_crawled_data)
    indexer.build_index(sample_crawled_data)

    # The index should be the same after rebuilding, not accumulating counts from previous builds.
    assert indexer.inverted_index['hello']['http://quotes.toscrape.com/page/1/']['frequency'] == 2

# Test generated by ChatGPT to test complex punctuation.
def test_complex_punctuation(indexer):
    data = [{
        'url': 'test',
        'text': "hello-world it's test_case"
    }]
    index = indexer.build_index(data)

    assert 'helloworld' in index  # depends on your design
    assert 'its' in index

def test_load_index_success(indexer):
    """
    Tests that a valid JSON file is loaded successfully into memory.
    """
    # 1. Manually write a valid JSON file to temporary test path.
    valid_data = {"hello": {"http://quotes.toscrape.com/page/1/": {"frequency": 1, "positions": [0]}}}

    os.makedirs(os.path.dirname(indexer.index_file_path), exist_ok=True)
    with open(indexer.index_file_path, 'w', encoding='utf-8') as f:
        json.dump(valid_data, f)

    # 2. Call the load method.
    result = indexer.load_index()

    # 3. It should return True and the data should be in memory.
    assert result is True
    assert indexer.inverted_index == valid_data

def test_load_index_missing_file(indexer):
    """
    Tests that loading fails gracefully if the index file does not exist.
    """
    # 1. Ensure the file path definitely doesn't exist.
    if os.path.exists(indexer.index_file_path):
        os.remove(indexer.index_file_path)

    # 2. Call the load method.
    result = indexer.load_index()

    # 3. It should return False and the index should remain empty.
    assert result is False
    assert indexer.inverted_index == {}

def test_load_index_corrupted_json(indexer):
    """
    Tests that loading fails gracefully if the file contains corrupt JSON content.
    """
    # 1. Write malformed text (not valid JSON) to the target file.
    os.makedirs(os.path.dirname(indexer.index_file_path), exist_ok=True)
    with open(indexer.index_file_path, 'w', encoding='utf-8') as f:
        f.write("{ this is not valid json! 'missing_quotes': 123")
        
    # 2. Call the load method
    result = indexer.load_index()
    
    # 3. It should return False because of the JSONDecodeError
    assert result is False
    assert indexer.inverted_index == {}
